version: '3.8'

services:
  app:
    image: ms-calcula-preco-tarifado:latest
    build:
      context: src/main/resources/docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/calculo
      SPRING_DATASOURCE_USERNAME: calculo
      SPRING_DATASOURCE_PASSWORD: calculo
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: calculo
      MYSQL_USER: calculo
      MYSQL_PASSWORD: calculo
      MYSQL_ROOT_PASSWORD: calculo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
