spring:
  messages: encoding=UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:h2:mem:calculo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: calculo
    password: calculo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console



management:
  endpoint:
    health:
      show-components: always
    logfile:
      enabled: true
  endpoints:
    web:
      base-path: /v1/actuator
      exposure:
        include: actuator,logfile,metrics,health,info

tax:
  rates:
    VIDA:
      - 0.01
      - 0.022
      - 0.00
    AUTO:
      - 0.055
      - 0.04
      - 0.01
    VIAGEM:
      - 0.02
      - 0.04
      - 0.01
    RESIDENCIAL:
      - 0.04
      - 0.00
      - 0.03
    PATRIMONIAL:
      - 0.05
      - 0.03
      - 0.00
